{
  "uid" : "ba7c1d2755b89366",
  "name" : "Home page - smoke test",
  "fullName" : "tests.ui.test_search.TestWeb#test_homepage_title1",
  "historyId" : "0e03a480debcb54dd0ad4bed14f612d2",
  "time" : {
    "start" : 1649175520976,
    "stop" : 1649175521675,
    "duration" : 699
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "web_setup",
    "time" : {
      "start" : 1649175520419,
      "stop" : 1649175520975,
      "duration" : 556
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1649175518469,
      "stop" : 1649175518530,
      "duration" : 61
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1649175520419,
      "stop" : 1649175520419,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "web_setup::0",
    "time" : {
      "start" : 1649175521676,
      "stop" : 1649175521774,
      "duration" : 98
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('web_setup')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_search"
  }, {
    "name" : "subSuite",
    "value" : "TestWeb"
  }, {
    "name" : "host",
    "value" : "fv-az290-11"
  }, {
    "name" : "thread",
    "value" : "3480-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_search"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 16,
        "skipped" : 0,
        "passed" : 15,
        "unknown" : 0,
        "total" : 31
      },
      "items" : [ {
        "uid" : "7f129906622f519c",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/21//#testresult/7f129906622f519c",
        "status" : "passed",
        "time" : {
          "start" : 1649175050371,
          "stop" : 1649175051133,
          "duration" : 762
        }
      }, {
        "uid" : "f048c3d172b653af",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/f048c3d172b653af",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13a06a8e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649174531649,
          "stop" : 1649174531649,
          "duration" : 0
        }
      }, {
        "uid" : "1748c91517fa2aa1",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/1748c91517fa2aa1",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b9e05210>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649173716407,
          "stop" : 1649173716407,
          "duration" : 0
        }
      }, {
        "uid" : "1ed6dbba97766069",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/1ed6dbba97766069",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfa6068e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649173130729,
          "stop" : 1649173130729,
          "duration" : 0
        }
      }, {
        "uid" : "4672f4fbbebe6a39",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/15//#testresult/4672f4fbbebe6a39",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1481374e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649172350238,
          "stop" : 1649172350238,
          "duration" : 0
        }
      }, {
        "uid" : "50379df99b9a0eb",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/50379df99b9a0eb",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21a3e4e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649170174976,
          "stop" : 1649170174976,
          "duration" : 0
        }
      }, {
        "uid" : "accf06d18493b36",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/11//#testresult/accf06d18493b36",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba64726620>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649167885162,
          "stop" : 1649167885162,
          "duration" : 0
        }
      }, {
        "uid" : "44ca7c89755b90c4",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/10//#testresult/44ca7c89755b90c4",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b14fca860>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649166993086,
          "stop" : 1649166993086,
          "duration" : 0
        }
      }, {
        "uid" : "b7169c05b242a5ef",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/9//#testresult/b7169c05b242a5ef",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04e8582680>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649166018410,
          "stop" : 1649166018410,
          "duration" : 0
        }
      }, {
        "uid" : "b99cf69d7d6efac7",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/b99cf69d7d6efac7",
        "status" : "passed",
        "time" : {
          "start" : 1649165665784,
          "stop" : 1649165666438,
          "duration" : 654
        }
      }, {
        "uid" : "d48ef0ca2afb7bd6",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/d48ef0ca2afb7bd6",
        "status" : "passed",
        "time" : {
          "start" : 1649165604776,
          "stop" : 1649165605600,
          "duration" : 824
        }
      }, {
        "uid" : "44264753d782984",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/7//#testresult/44264753d782984",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69c035a5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649165599608,
          "stop" : 1649165599608,
          "duration" : 0
        }
      }, {
        "uid" : "c2f1ec86a1090425",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/c2f1ec86a1090425",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe68076be50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649110750016,
          "stop" : 1649110750016,
          "duration" : 0
        }
      }, {
        "uid" : "2597cc5507ee15eb",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/2597cc5507ee15eb",
        "status" : "passed",
        "time" : {
          "start" : 1649110731073,
          "stop" : 1649110731815,
          "duration" : 742
        }
      }, {
        "uid" : "bb45db284b347903",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/17//#testresult/bb45db284b347903",
        "status" : "passed",
        "time" : {
          "start" : 1649109323001,
          "stop" : 1649109323755,
          "duration" : 754
        }
      }, {
        "uid" : "a49614a343ed6414",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/a49614a343ed6414",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff12e50a2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649109176418,
          "stop" : 1649109176418,
          "duration" : 0
        }
      }, {
        "uid" : "e7fc2e1c90d00444",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/e7fc2e1c90d00444",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f565220a290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649109036771,
          "stop" : 1649109036771,
          "duration" : 0
        }
      }, {
        "uid" : "1c57645aa77ff170",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/14//#testresult/1c57645aa77ff170",
        "status" : "passed",
        "time" : {
          "start" : 1649108805617,
          "stop" : 1649108806460,
          "duration" : 843
        }
      }, {
        "uid" : "12198787a79adf84",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/12198787a79adf84",
        "status" : "passed",
        "time" : {
          "start" : 1649108546412,
          "stop" : 1649108547347,
          "duration" : 935
        }
      }, {
        "uid" : "b3f0881205416860",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/1//#testresult/b3f0881205416860",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14dcffd30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649108545068,
          "stop" : 1649108545068,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.usefixtures('web_setup')" ]
  },
  "source" : "ba7c1d2755b89366.json",
  "parameterValues" : [ ]
}