{
  "uid" : "1b666568ea3f07f2",
  "name" : "Home page - smoke test",
  "fullName" : "tests.ui.test_search.TestWeb#test_homepage_title1",
  "historyId" : "0e03a480debcb54dd0ad4bed14f612d2",
  "time" : {
    "start" : 1649270432088,
    "stop" : 1649270432825,
    "duration" : 737
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "browser",
    "time" : {
      "start" : 1649270431429,
      "stop" : 1649270431429,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "web_setup",
    "time" : {
      "start" : 1649270431429,
      "stop" : 1649270432088,
      "duration" : 659
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1649270429064,
      "stop" : 1649270429140,
      "duration" : 76
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "web_setup::0",
    "time" : {
      "start" : 1649270432825,
      "stop" : 1649270432941,
      "duration" : 116
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('web_setup')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_search"
  }, {
    "name" : "subSuite",
    "value" : "TestWeb"
  }, {
    "name" : "host",
    "value" : "fv-az399-409"
  }, {
    "name" : "thread",
    "value" : "3628-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_search"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 3,
        "skipped" : 0,
        "passed" : 2,
        "unknown" : 0,
        "total" : 5
      },
      "items" : [ {
        "uid" : "5f464444954c2410",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/5f464444954c2410",
        "status" : "passed",
        "time" : {
          "start" : 1649270047526,
          "stop" : 1649270048402,
          "duration" : 876
        }
      }, {
        "uid" : "fb43eb6fa9e194cd",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/fb43eb6fa9e194cd",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aeeb3d60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193829321,
          "stop" : 1649193829321,
          "duration" : 0
        }
      }, {
        "uid" : "1e54796264845f73",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1e54796264845f73",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a79e290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193204281,
          "stop" : 1649193204281,
          "duration" : 0
        }
      }, {
        "uid" : "edd22d2fdba54977",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/edd22d2fdba54977",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81be9bfd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649183948593,
          "stop" : 1649183948593,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.usefixtures('web_setup')" ]
  },
  "source" : "1b666568ea3f07f2.json",
  "parameterValues" : [ ]
}