{
  "uid" : "29c0d1d6ab5e1e59",
  "name" : "Home page - smoke test",
  "fullName" : "tests.ui.test_search.TestWeb#test_homepage_title13",
  "historyId" : "4c6a26788916d97b0c591def5d62e104",
  "time" : {
    "start" : 1649357467171,
    "stop" : 1649357467925,
    "duration" : 754
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "web_setup",
    "time" : {
      "start" : 1649357466523,
      "stop" : 1649357467170,
      "duration" : 647
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1649357454766,
      "stop" : 1649357454837,
      "duration" : 71
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1649357466523,
      "stop" : 1649357466523,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "web_setup::0",
    "time" : {
      "start" : 1649357467926,
      "stop" : 1649357468050,
      "duration" : 124
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('web_setup')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_search"
  }, {
    "name" : "subSuite",
    "value" : "TestWeb"
  }, {
    "name" : "host",
    "value" : "fv-az504-908"
  }, {
    "name" : "thread",
    "value" : "3603-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_search"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 5,
        "unknown" : 0,
        "total" : 9
      },
      "items" : [ {
        "uid" : "1fe449cf5804c2f",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/1fe449cf5804c2f",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7dc199b10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649357455889,
          "stop" : 1649357455889,
          "duration" : 0
        }
      }, {
        "uid" : "6a077761940676a7",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/6a077761940676a7",
        "status" : "passed",
        "time" : {
          "start" : 1649270527183,
          "stop" : 1649270527862,
          "duration" : 679
        }
      }, {
        "uid" : "8bf5f3b8fd2657ac",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/8bf5f3b8fd2657ac",
        "status" : "passed",
        "time" : {
          "start" : 1649270496845,
          "stop" : 1649270497707,
          "duration" : 862
        }
      }, {
        "uid" : "a6f56feae015ec53",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/a6f56feae015ec53",
        "status" : "passed",
        "time" : {
          "start" : 1649270435328,
          "stop" : 1649270436094,
          "duration" : 766
        }
      }, {
        "uid" : "2e50eafc05423496",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/2e50eafc05423496",
        "status" : "passed",
        "time" : {
          "start" : 1649270051243,
          "stop" : 1649270052148,
          "duration" : 905
        }
      }, {
        "uid" : "671ec5eee2bb2384",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/671ec5eee2bb2384",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43ada42170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193829742,
          "stop" : 1649193829742,
          "duration" : 0
        }
      }, {
        "uid" : "de171ede74f74294",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/de171ede74f74294",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a766200>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193204538,
          "stop" : 1649193204538,
          "duration" : 0
        }
      }, {
        "uid" : "17cf4ecc9a11bd15",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/17cf4ecc9a11bd15",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bd586170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649183949127,
          "stop" : 1649183949127,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.usefixtures('web_setup')" ]
  },
  "source" : "29c0d1d6ab5e1e59.json",
  "parameterValues" : [ ]
}