{
  "uid" : "d53b0525ae048c23",
  "name" : "Home page - smoke test",
  "fullName" : "tests.ui.test_search.TestWeb#test_homepage_title12",
  "historyId" : "b2e57dac307fb5f5a232440dbae3faf9",
  "time" : {
    "start" : 1649357465641,
    "stop" : 1649357466409,
    "duration" : 768
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1649357454766,
      "stop" : 1649357454837,
      "duration" : 71
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1649357465114,
      "stop" : 1649357465114,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "web_setup",
    "time" : {
      "start" : 1649357465114,
      "stop" : 1649357465641,
      "duration" : 527
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "web_setup::0",
    "time" : {
      "start" : 1649357466409,
      "stop" : 1649357466520,
      "duration" : 111
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('web_setup')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.ui"
  }, {
    "name" : "suite",
    "value" : "test_search"
  }, {
    "name" : "subSuite",
    "value" : "TestWeb"
  }, {
    "name" : "host",
    "value" : "fv-az504-908"
  }, {
    "name" : "thread",
    "value" : "3603-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.test_search"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 5,
        "unknown" : 0,
        "total" : 9
      },
      "items" : [ {
        "uid" : "4d6765cc078b2b8d",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/4d6765cc078b2b8d",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7ddcf3670>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649357455669,
          "stop" : 1649357455669,
          "duration" : 0
        }
      }, {
        "uid" : "e06c484ff2fb631a",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/e06c484ff2fb631a",
        "status" : "passed",
        "time" : {
          "start" : 1649270525953,
          "stop" : 1649270526597,
          "duration" : 644
        }
      }, {
        "uid" : "388de20f20159f98",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/388de20f20159f98",
        "status" : "passed",
        "time" : {
          "start" : 1649270495180,
          "stop" : 1649270496042,
          "duration" : 862
        }
      }, {
        "uid" : "a767740607a08e7e",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/a767740607a08e7e",
        "status" : "passed",
        "time" : {
          "start" : 1649270433719,
          "stop" : 1649270434504,
          "duration" : 785
        }
      }, {
        "uid" : "503b0ac0b4199d53",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/503b0ac0b4199d53",
        "status" : "passed",
        "time" : {
          "start" : 1649270049308,
          "stop" : 1649270050205,
          "duration" : 897
        }
      }, {
        "uid" : "3c03ebe525b29cad",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/3c03ebe525b29cad",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aff65c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193829522,
          "stop" : 1649193829522,
          "duration" : 0
        }
      }, {
        "uid" : "1d7beeccc4082119",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1d7beeccc4082119",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a6b1b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649193204415,
          "stop" : 1649193204415,
          "duration" : 0
        }
      }, {
        "uid" : "1f2fafe0e93dfd13",
        "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/1f2fafe0e93dfd13",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfa61c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1649183948831,
          "stop" : 1649183948831,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.usefixtures('web_setup')" ]
  },
  "source" : "d53b0525ae048c23.json",
  "parameterValues" : [ ]
}