{
  "0e03a480debcb54dd0ad4bed14f612d2" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 3,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "fb43eb6fa9e194cd",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/fb43eb6fa9e194cd",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aeeb3d60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829321,
        "stop" : 1649193829321,
        "duration" : 0
      }
    }, {
      "uid" : "1e54796264845f73",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1e54796264845f73",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a79e290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204281,
        "stop" : 1649193204281,
        "duration" : 0
      }
    }, {
      "uid" : "edd22d2fdba54977",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/edd22d2fdba54977",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81be9bfd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948593,
        "stop" : 1649183948593,
        "duration" : 0
      }
    } ]
  },
  "4c6a26788916d97b0c591def5d62e104" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 3,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "671ec5eee2bb2384",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/671ec5eee2bb2384",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43ada42170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829742,
        "stop" : 1649193829742,
        "duration" : 0
      }
    }, {
      "uid" : "de171ede74f74294",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/de171ede74f74294",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a766200>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204538,
        "stop" : 1649193204538,
        "duration" : 0
      }
    }, {
      "uid" : "17cf4ecc9a11bd15",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/17cf4ecc9a11bd15",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bd586170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183949127,
        "stop" : 1649183949127,
        "duration" : 0
      }
    } ]
  },
  "b2e57dac307fb5f5a232440dbae3faf9" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 3,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "3c03ebe525b29cad",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/3c03ebe525b29cad",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aff65c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829522,
        "stop" : 1649193829522,
        "duration" : 0
      }
    }, {
      "uid" : "1d7beeccc4082119",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1d7beeccc4082119",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a6b1b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204415,
        "stop" : 1649193204415,
        "duration" : 0
      }
    }, {
      "uid" : "1f2fafe0e93dfd13",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/1f2fafe0e93dfd13",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfa61c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948831,
        "stop" : 1649183948831,
        "duration" : 0
      }
    } ]
  },
  "65fd2b4dfcf9c1e5ba26298719a99a88" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 3,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "e29f31b8eb632bfe",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/e29f31b8eb632bfe",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43b04448b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829046,
        "stop" : 1649193829046,
        "duration" : 0
      }
    }, {
      "uid" : "6f9b6614bab93134",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/6f9b6614bab93134",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6d1ec850>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204073,
        "stop" : 1649193204073,
        "duration" : 0
      }
    }, {
      "uid" : "359733bff7cfc889",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/359733bff7cfc889",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfcc48b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948318,
        "stop" : 1649183948318,
        "duration" : 0
      }
    } ]
  }
}