{
  "0e03a480debcb54dd0ad4bed14f612d2" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 5,
      "skipped" : 0,
      "passed" : 5,
      "unknown" : 0,
      "total" : 10
    },
    "items" : [ {
      "uid" : "48a1a523c10d5ea",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/48a1a523c10d5ea",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b20366680>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357741657,
        "stop" : 1649357741657,
        "duration" : 0
      }
    }, {
      "uid" : "516404768d89335e",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/516404768d89335e",
      "status" : "passed",
      "time" : {
        "start" : 1649357464234,
        "stop" : 1649357464994,
        "duration" : 760
      }
    }, {
      "uid" : "fb29f519a93e34d9",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/fb29f519a93e34d9",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7dc01b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357455458,
        "stop" : 1649357455458,
        "duration" : 0
      }
    }, {
      "uid" : "cc53dc3157efc1a8",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/cc53dc3157efc1a8",
      "status" : "passed",
      "time" : {
        "start" : 1649270524762,
        "stop" : 1649270525374,
        "duration" : 612
      }
    }, {
      "uid" : "61fdc531988fc40b",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/61fdc531988fc40b",
      "status" : "passed",
      "time" : {
        "start" : 1649270493605,
        "stop" : 1649270494457,
        "duration" : 852
      }
    }, {
      "uid" : "1b666568ea3f07f2",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/1b666568ea3f07f2",
      "status" : "passed",
      "time" : {
        "start" : 1649270432088,
        "stop" : 1649270432825,
        "duration" : 737
      }
    }, {
      "uid" : "5f464444954c2410",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/5f464444954c2410",
      "status" : "passed",
      "time" : {
        "start" : 1649270047526,
        "stop" : 1649270048402,
        "duration" : 876
      }
    }, {
      "uid" : "fb43eb6fa9e194cd",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/fb43eb6fa9e194cd",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aeeb3d60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829321,
        "stop" : 1649193829321,
        "duration" : 0
      }
    }, {
      "uid" : "1e54796264845f73",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1e54796264845f73",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a79e290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204281,
        "stop" : 1649193204281,
        "duration" : 0
      }
    }, {
      "uid" : "edd22d2fdba54977",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/edd22d2fdba54977",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81be9bfd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948593,
        "stop" : 1649183948593,
        "duration" : 0
      }
    } ]
  },
  "4c6a26788916d97b0c591def5d62e104" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 5,
      "skipped" : 0,
      "passed" : 5,
      "unknown" : 0,
      "total" : 10
    },
    "items" : [ {
      "uid" : "af2c66b540161b19",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/af2c66b540161b19",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b202d7160>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357742291,
        "stop" : 1649357742291,
        "duration" : 0
      }
    }, {
      "uid" : "29c0d1d6ab5e1e59",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/29c0d1d6ab5e1e59",
      "status" : "passed",
      "time" : {
        "start" : 1649357467171,
        "stop" : 1649357467925,
        "duration" : 754
      }
    }, {
      "uid" : "1fe449cf5804c2f",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/1fe449cf5804c2f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7dc199b10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357455889,
        "stop" : 1649357455889,
        "duration" : 0
      }
    }, {
      "uid" : "6a077761940676a7",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/6a077761940676a7",
      "status" : "passed",
      "time" : {
        "start" : 1649270527183,
        "stop" : 1649270527862,
        "duration" : 679
      }
    }, {
      "uid" : "8bf5f3b8fd2657ac",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/8bf5f3b8fd2657ac",
      "status" : "passed",
      "time" : {
        "start" : 1649270496845,
        "stop" : 1649270497707,
        "duration" : 862
      }
    }, {
      "uid" : "a6f56feae015ec53",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/a6f56feae015ec53",
      "status" : "passed",
      "time" : {
        "start" : 1649270435328,
        "stop" : 1649270436094,
        "duration" : 766
      }
    }, {
      "uid" : "2e50eafc05423496",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/2e50eafc05423496",
      "status" : "passed",
      "time" : {
        "start" : 1649270051243,
        "stop" : 1649270052148,
        "duration" : 905
      }
    }, {
      "uid" : "671ec5eee2bb2384",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/671ec5eee2bb2384",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43ada42170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829742,
        "stop" : 1649193829742,
        "duration" : 0
      }
    }, {
      "uid" : "de171ede74f74294",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/de171ede74f74294",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a766200>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204538,
        "stop" : 1649193204538,
        "duration" : 0
      }
    }, {
      "uid" : "17cf4ecc9a11bd15",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/17cf4ecc9a11bd15",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bd586170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183949127,
        "stop" : 1649183949127,
        "duration" : 0
      }
    } ]
  },
  "e8da01fa517f1b4876d8ab0a78459a63" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "3e51be83befa4986",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/3e51be83befa4986",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b20221db0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357740619,
        "stop" : 1649357740619,
        "duration" : 0
      }
    }, {
      "uid" : "df67feb83a036aea",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/df67feb83a036aea",
      "status" : "passed",
      "time" : {
        "start" : 1649357459133,
        "stop" : 1649357459949,
        "duration" : 816
      }
    }, {
      "uid" : "ddf079f1bec589c0",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/ddf079f1bec589c0",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7de5b6e90>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357454481,
        "stop" : 1649357454481,
        "duration" : 0
      }
    } ]
  },
  "b2e57dac307fb5f5a232440dbae3faf9" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 5,
      "skipped" : 0,
      "passed" : 5,
      "unknown" : 0,
      "total" : 10
    },
    "items" : [ {
      "uid" : "d1c3796dd4e4632f",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/d1c3796dd4e4632f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b20206590>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357741947,
        "stop" : 1649357741947,
        "duration" : 0
      }
    }, {
      "uid" : "d53b0525ae048c23",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/d53b0525ae048c23",
      "status" : "passed",
      "time" : {
        "start" : 1649357465641,
        "stop" : 1649357466409,
        "duration" : 768
      }
    }, {
      "uid" : "4d6765cc078b2b8d",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/4d6765cc078b2b8d",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7ddcf3670>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357455669,
        "stop" : 1649357455669,
        "duration" : 0
      }
    }, {
      "uid" : "e06c484ff2fb631a",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/e06c484ff2fb631a",
      "status" : "passed",
      "time" : {
        "start" : 1649270525953,
        "stop" : 1649270526597,
        "duration" : 644
      }
    }, {
      "uid" : "388de20f20159f98",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/388de20f20159f98",
      "status" : "passed",
      "time" : {
        "start" : 1649270495180,
        "stop" : 1649270496042,
        "duration" : 862
      }
    }, {
      "uid" : "a767740607a08e7e",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/a767740607a08e7e",
      "status" : "passed",
      "time" : {
        "start" : 1649270433719,
        "stop" : 1649270434504,
        "duration" : 785
      }
    }, {
      "uid" : "503b0ac0b4199d53",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/503b0ac0b4199d53",
      "status" : "passed",
      "time" : {
        "start" : 1649270049308,
        "stop" : 1649270050205,
        "duration" : 897
      }
    }, {
      "uid" : "3c03ebe525b29cad",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/3c03ebe525b29cad",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43aff65c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829522,
        "stop" : 1649193829522,
        "duration" : 0
      }
    }, {
      "uid" : "1d7beeccc4082119",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/1d7beeccc4082119",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6a6b1b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204415,
        "stop" : 1649193204415,
        "duration" : 0
      }
    }, {
      "uid" : "1f2fafe0e93dfd13",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/1f2fafe0e93dfd13",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfa61c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948831,
        "stop" : 1649183948831,
        "duration" : 0
      }
    } ]
  },
  "33fdd5ef7ef896960a4010145e06ee0f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "241b98a2bad9dcec",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/241b98a2bad9dcec",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b22d4c9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357739831,
        "stop" : 1649357739831,
        "duration" : 0
      }
    }, {
      "uid" : "63334fcee891fbfe",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/63334fcee891fbfe",
      "status" : "passed",
      "time" : {
        "start" : 1649357456105,
        "stop" : 1649357456879,
        "duration" : 774
      }
    }, {
      "uid" : "2bada41ae6def16",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/2bada41ae6def16",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7ddcf0df0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357454026,
        "stop" : 1649357454026,
        "duration" : 0
      }
    } ]
  },
  "18773396885e1235c81346d5f15e998f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "3ca2e5f770cd9871",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/3ca2e5f770cd9871",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b217fe560>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357740202,
        "stop" : 1649357740202,
        "duration" : 0
      }
    }, {
      "uid" : "5974c59fb3c33c8e",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/5974c59fb3c33c8e",
      "status" : "passed",
      "time" : {
        "start" : 1649357457636,
        "stop" : 1649357458405,
        "duration" : 769
      }
    }, {
      "uid" : "fe86eea5dfba0eb9",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/fe86eea5dfba0eb9",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7dd5ee440>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357454273,
        "stop" : 1649357454273,
        "duration" : 0
      }
    } ]
  },
  "65fd2b4dfcf9c1e5ba26298719a99a88" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 5,
      "skipped" : 0,
      "passed" : 5,
      "unknown" : 0,
      "total" : 10
    },
    "items" : [ {
      "uid" : "a8c63ccab8143dfb",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/a8c63ccab8143dfb",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b22d92500>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357741342,
        "stop" : 1649357741342,
        "duration" : 0
      }
    }, {
      "uid" : "df5b65a943e8f681",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/df5b65a943e8f681",
      "status" : "passed",
      "time" : {
        "start" : 1649357462199,
        "stop" : 1649357463590,
        "duration" : 1391
      }
    }, {
      "uid" : "61e2eee5f78ae388",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/61e2eee5f78ae388",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7de6296c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357455103,
        "stop" : 1649357455103,
        "duration" : 0
      }
    }, {
      "uid" : "6552e52cae7ee8a5",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/27//#testresult/6552e52cae7ee8a5",
      "status" : "passed",
      "time" : {
        "start" : 1649270523516,
        "stop" : 1649270524159,
        "duration" : 643
      }
    }, {
      "uid" : "a51774aab7b6de81",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/26//#testresult/a51774aab7b6de81",
      "status" : "passed",
      "time" : {
        "start" : 1649270491851,
        "stop" : 1649270492789,
        "duration" : 938
      }
    }, {
      "uid" : "1f2c22656d30697f",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/25//#testresult/1f2c22656d30697f",
      "status" : "passed",
      "time" : {
        "start" : 1649270430452,
        "stop" : 1649270431304,
        "duration" : 852
      }
    }, {
      "uid" : "869969a1085ac38",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/24//#testresult/869969a1085ac38",
      "status" : "passed",
      "time" : {
        "start" : 1649270045553,
        "stop" : 1649270046557,
        "duration" : 1004
      }
    }, {
      "uid" : "e29f31b8eb632bfe",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/41//#testresult/e29f31b8eb632bfe",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43b04448b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193829046,
        "stop" : 1649193829046,
        "duration" : 0
      }
    }, {
      "uid" : "6f9b6614bab93134",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/39//#testresult/6f9b6614bab93134",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a6d1ec850>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649193204073,
        "stop" : 1649193204073,
        "duration" : 0
      }
    }, {
      "uid" : "359733bff7cfc889",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/359733bff7cfc889",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfcc48b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948318,
        "stop" : 1649183948318,
        "duration" : 0
      }
    } ]
  },
  "3f65c99dd0b5252518dde9a7f74d47d5" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "7ce9316cb73270db",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/68//#testresult/7ce9316cb73270db",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b21951390>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357740945,
        "stop" : 1649357740945,
        "duration" : 0
      }
    }, {
      "uid" : "959ba5fd081ce784",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/29//#testresult/959ba5fd081ce784",
      "status" : "passed",
      "time" : {
        "start" : 1649357460685,
        "stop" : 1649357461493,
        "duration" : 808
      }
    }, {
      "uid" : "5e79faacdacff5ad",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/67//#testresult/5e79faacdacff5ad",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc7dd63d420>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649357454756,
        "stop" : 1649357454756,
        "duration" : 0
      }
    } ]
  }
}