{
  "0e03a480debcb54dd0ad4bed14f612d2" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 16,
      "skipped" : 0,
      "passed" : 14,
      "unknown" : 0,
      "total" : 30
    },
    "items" : [ {
      "uid" : "7f129906622f519c",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/21//#testresult/7f129906622f519c",
      "status" : "passed",
      "time" : {
        "start" : 1649175050371,
        "stop" : 1649175051133,
        "duration" : 762
      }
    }, {
      "uid" : "f048c3d172b653af",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/f048c3d172b653af",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13a06a8e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649174531649,
        "stop" : 1649174531649,
        "duration" : 0
      }
    }, {
      "uid" : "1748c91517fa2aa1",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/1748c91517fa2aa1",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b9e05210>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173716407,
        "stop" : 1649173716407,
        "duration" : 0
      }
    }, {
      "uid" : "1ed6dbba97766069",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/1ed6dbba97766069",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfa6068e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173130729,
        "stop" : 1649173130729,
        "duration" : 0
      }
    }, {
      "uid" : "4672f4fbbebe6a39",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/15//#testresult/4672f4fbbebe6a39",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1481374e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649172350238,
        "stop" : 1649172350238,
        "duration" : 0
      }
    }, {
      "uid" : "50379df99b9a0eb",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/50379df99b9a0eb",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21a3e4e50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649170174976,
        "stop" : 1649170174976,
        "duration" : 0
      }
    }, {
      "uid" : "accf06d18493b36",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/11//#testresult/accf06d18493b36",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba64726620>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649167885162,
        "stop" : 1649167885162,
        "duration" : 0
      }
    }, {
      "uid" : "44ca7c89755b90c4",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/10//#testresult/44ca7c89755b90c4",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b14fca860>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166993086,
        "stop" : 1649166993086,
        "duration" : 0
      }
    }, {
      "uid" : "b7169c05b242a5ef",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/9//#testresult/b7169c05b242a5ef",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04e8582680>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166018410,
        "stop" : 1649166018410,
        "duration" : 0
      }
    }, {
      "uid" : "b99cf69d7d6efac7",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/b99cf69d7d6efac7",
      "status" : "passed",
      "time" : {
        "start" : 1649165665784,
        "stop" : 1649165666438,
        "duration" : 654
      }
    }, {
      "uid" : "d48ef0ca2afb7bd6",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/d48ef0ca2afb7bd6",
      "status" : "passed",
      "time" : {
        "start" : 1649165604776,
        "stop" : 1649165605600,
        "duration" : 824
      }
    }, {
      "uid" : "44264753d782984",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/7//#testresult/44264753d782984",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69c035a5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649165599608,
        "stop" : 1649165599608,
        "duration" : 0
      }
    }, {
      "uid" : "c2f1ec86a1090425",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/c2f1ec86a1090425",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe68076be50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649110750016,
        "stop" : 1649110750016,
        "duration" : 0
      }
    }, {
      "uid" : "2597cc5507ee15eb",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/2597cc5507ee15eb",
      "status" : "passed",
      "time" : {
        "start" : 1649110731073,
        "stop" : 1649110731815,
        "duration" : 742
      }
    }, {
      "uid" : "bb45db284b347903",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/17//#testresult/bb45db284b347903",
      "status" : "passed",
      "time" : {
        "start" : 1649109323001,
        "stop" : 1649109323755,
        "duration" : 754
      }
    }, {
      "uid" : "a49614a343ed6414",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/a49614a343ed6414",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff12e50a2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109176418,
        "stop" : 1649109176418,
        "duration" : 0
      }
    }, {
      "uid" : "e7fc2e1c90d00444",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/e7fc2e1c90d00444",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f565220a290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109036771,
        "stop" : 1649109036771,
        "duration" : 0
      }
    }, {
      "uid" : "1c57645aa77ff170",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/14//#testresult/1c57645aa77ff170",
      "status" : "passed",
      "time" : {
        "start" : 1649108805617,
        "stop" : 1649108806460,
        "duration" : 843
      }
    }, {
      "uid" : "12198787a79adf84",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/12198787a79adf84",
      "status" : "passed",
      "time" : {
        "start" : 1649108546412,
        "stop" : 1649108547347,
        "duration" : 935
      }
    }, {
      "uid" : "b3f0881205416860",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/1//#testresult/b3f0881205416860",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14dcffd30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649108545068,
        "stop" : 1649108545068,
        "duration" : 0
      }
    } ]
  },
  "4c6a26788916d97b0c591def5d62e104" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 7,
      "skipped" : 0,
      "passed" : 12,
      "unknown" : 0,
      "total" : 19
    },
    "items" : [ {
      "uid" : "995d787eb4285eab",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/21//#testresult/995d787eb4285eab",
      "status" : "passed",
      "time" : {
        "start" : 1649175054218,
        "stop" : 1649175055445,
        "duration" : 1227
      }
    }, {
      "uid" : "6d9a128ba38d75e9",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/6d9a128ba38d75e9",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe67e44e1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649110750407,
        "stop" : 1649110750407,
        "duration" : 0
      }
    }, {
      "uid" : "fb93cba2a679fc12",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/fb93cba2a679fc12",
      "status" : "passed",
      "time" : {
        "start" : 1649110733766,
        "stop" : 1649110734391,
        "duration" : 625
      }
    }, {
      "uid" : "27b30639d46f7642",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/17//#testresult/27b30639d46f7642",
      "status" : "passed",
      "time" : {
        "start" : 1649109325988,
        "stop" : 1649109326601,
        "duration" : 613
      }
    }, {
      "uid" : "e557ccd94148afb",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/e557ccd94148afb",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff12e4de1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109177079,
        "stop" : 1649109177079,
        "duration" : 0
      }
    }, {
      "uid" : "dc76ae02554d0aca",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/dc76ae02554d0aca",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56521da200>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109037204,
        "stop" : 1649109037204,
        "duration" : 0
      }
    }, {
      "uid" : "e7343f326b7fdc6c",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/14//#testresult/e7343f326b7fdc6c",
      "status" : "passed",
      "time" : {
        "start" : 1649108808828,
        "stop" : 1649108809575,
        "duration" : 747
      }
    }, {
      "uid" : "908846b93301592a",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/908846b93301592a",
      "status" : "passed",
      "time" : {
        "start" : 1649108549718,
        "stop" : 1649108550489,
        "duration" : 771
      }
    }, {
      "uid" : "1fc1fcc387eb4cbe",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/1//#testresult/1fc1fcc387eb4cbe",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14c8c61d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649108545433,
        "stop" : 1649108545433,
        "duration" : 0
      }
    }, {
      "uid" : "2ee38d395c1dd3a1",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/11//#testresult/2ee38d395c1dd3a1",
      "status" : "passed",
      "time" : {
        "start" : 1649108214302,
        "stop" : 1649108217073,
        "duration" : 2771
      }
    }, {
      "uid" : "eec675ba93b865fd",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/10//#testresult/eec675ba93b865fd",
      "status" : "passed",
      "time" : {
        "start" : 1649107868330,
        "stop" : 1649107869041,
        "duration" : 711
      }
    }, {
      "uid" : "91ef0422c52c080",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/9//#testresult/91ef0422c52c080",
      "status" : "passed",
      "time" : {
        "start" : 1649107519146,
        "stop" : 1649107519892,
        "duration" : 746
      }
    }, {
      "uid" : "c49c1518bec25704",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/8//#testresult/c49c1518bec25704",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x56191941dad3 <unknown>\n#1 0x56191917d568 <unknown>\n#2 0x5619191a0b37 <unknown>\n#3 0x56191919c23a <unknown>\n#4 0x5619191d72ba <unknown>\n#5 0x5619191d14e3 <unknown>\n#6 0x5619191a6d1a <unknown>\n#7 0x5619191a7e75 <unknown>\n#8 0x56191944befd <unknown>\n#9 0x56191946519b <unknown>\n#10 0x56191944dc65 <unknown>\n#11 0x561919465ec8 <unknown>\n#12 0x561919441360 <unknown>\n#13 0x561919481a68 <unknown>\n#14 0x561919481be8 <unknown>\n#15 0x56191949b7fd <unknown>\n#16 0x7f1dfa3f4609 <unknown>",
      "time" : {
        "start" : 1649107303973,
        "stop" : 1649107303973,
        "duration" : 0
      }
    }, {
      "uid" : "562eecd077a01d",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/7//#testresult/562eecd077a01d",
      "status" : "passed",
      "time" : {
        "start" : 1649106456854,
        "stop" : 1649106457689,
        "duration" : 835
      }
    }, {
      "uid" : "25a04c666a9191d0",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/25a04c666a9191d0",
      "status" : "passed",
      "time" : {
        "start" : 1649106441517,
        "stop" : 1649106442118,
        "duration" : 601
      }
    }, {
      "uid" : "5e378b6c60343aba",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/5//#testresult/5e378b6c60343aba",
      "status" : "passed",
      "time" : {
        "start" : 1649106389347,
        "stop" : 1649106390143,
        "duration" : 796
      }
    }, {
      "uid" : "e7dd04b518473d21",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/e7dd04b518473d21",
      "status" : "passed",
      "time" : {
        "start" : 1649105941257,
        "stop" : 1649105941913,
        "duration" : 656
      }
    }, {
      "uid" : "b8d27bdb16a7d0aa",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/b8d27bdb16a7d0aa",
      "status" : "broken",
      "statusDetails" : "NameError: name 'webdriver' is not defined",
      "time" : {
        "start" : 1649105743283,
        "stop" : 1649105743283,
        "duration" : 0
      }
    }, {
      "uid" : "1145381f9c1dd9f5",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/2//#testresult/1145381f9c1dd9f5",
      "status" : "broken",
      "statusDetails" : "ValueError: no option named '--host'",
      "time" : {
        "start" : 1649105573035,
        "stop" : 1649105573035,
        "duration" : 0
      }
    } ]
  },
  "b2e57dac307fb5f5a232440dbae3faf9" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 16,
      "skipped" : 0,
      "passed" : 14,
      "unknown" : 0,
      "total" : 30
    },
    "items" : [ {
      "uid" : "9a360a7fbae31cf5",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/21//#testresult/9a360a7fbae31cf5",
      "status" : "passed",
      "time" : {
        "start" : 1649175051808,
        "stop" : 1649175052954,
        "duration" : 1146
      }
    }, {
      "uid" : "85176b0da07a2072",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/85176b0da07a2072",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f139dd274c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649174531870,
        "stop" : 1649174531870,
        "duration" : 0
      }
    }, {
      "uid" : "c90c21a3d6195101",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/c90c21a3d6195101",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b9b1b070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173716625,
        "stop" : 1649173716625,
        "duration" : 0
      }
    }, {
      "uid" : "8c59cc71b6ac3836",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/8c59cc71b6ac3836",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfa38b6f80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173131014,
        "stop" : 1649173131014,
        "duration" : 0
      }
    }, {
      "uid" : "e0cb9def87b0cf4f",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/15//#testresult/e0cb9def87b0cf4f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f147ebdb4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649172350467,
        "stop" : 1649172350467,
        "duration" : 0
      }
    }, {
      "uid" : "341e329e873da154",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/341e329e873da154",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb217c3af80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649170175223,
        "stop" : 1649170175223,
        "duration" : 0
      }
    }, {
      "uid" : "d292553850b41622",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/11//#testresult/d292553850b41622",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba61f4efb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649167885456,
        "stop" : 1649167885456,
        "duration" : 0
      }
    }, {
      "uid" : "597602b233a670ff",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/10//#testresult/597602b233a670ff",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b1269f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166993384,
        "stop" : 1649166993384,
        "duration" : 0
      }
    }, {
      "uid" : "eb23e78f8c357246",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/9//#testresult/eb23e78f8c357246",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04e8306fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166018724,
        "stop" : 1649166018724,
        "duration" : 0
      }
    }, {
      "uid" : "a42ce630d08e7e9a",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/a42ce630d08e7e9a",
      "status" : "passed",
      "time" : {
        "start" : 1649165667142,
        "stop" : 1649165667756,
        "duration" : 614
      }
    }, {
      "uid" : "e87c4f3c4cd0a787",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/e87c4f3c4cd0a787",
      "status" : "passed",
      "time" : {
        "start" : 1649165606391,
        "stop" : 1649165607180,
        "duration" : 789
      }
    }, {
      "uid" : "797e8845e1eb9d18",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/7//#testresult/797e8845e1eb9d18",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69bdb96140>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649165599849,
        "stop" : 1649165599849,
        "duration" : 0
      }
    }, {
      "uid" : "da9698e7d252f701",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/da9698e7d252f701",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe67e2e9b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649110750171,
        "stop" : 1649110750171,
        "duration" : 0
      }
    }, {
      "uid" : "d70bfedc64cc96aa",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/d70bfedc64cc96aa",
      "status" : "passed",
      "time" : {
        "start" : 1649110732518,
        "stop" : 1649110733136,
        "duration" : 618
      }
    }, {
      "uid" : "1ed5ab82131a62a8",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/17//#testresult/1ed5ab82131a62a8",
      "status" : "passed",
      "time" : {
        "start" : 1649109324543,
        "stop" : 1649109325214,
        "duration" : 671
      }
    }, {
      "uid" : "686ef213f880f490",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/686ef213f880f490",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff130a65c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109176744,
        "stop" : 1649109176744,
        "duration" : 0
      }
    }, {
      "uid" : "a2add1e3ce4238fc",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/a2add1e3ce4238fc",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5652119b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109036992,
        "stop" : 1649109036992,
        "duration" : 0
      }
    }, {
      "uid" : "e4a9c8f1fecf7a2d",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/14//#testresult/e4a9c8f1fecf7a2d",
      "status" : "passed",
      "time" : {
        "start" : 1649108807276,
        "stop" : 1649108808138,
        "duration" : 862
      }
    }, {
      "uid" : "d9a39cdf8658e06b",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/d9a39cdf8658e06b",
      "status" : "passed",
      "time" : {
        "start" : 1649108548138,
        "stop" : 1649108548882,
        "duration" : 744
      }
    }, {
      "uid" : "e135502b6f2567c",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/1//#testresult/e135502b6f2567c",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14eda1bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649108545242,
        "stop" : 1649108545242,
        "duration" : 0
      }
    } ]
  },
  "65fd2b4dfcf9c1e5ba26298719a99a88" : {
    "statistic" : {
      "failed" : 2,
      "broken" : 16,
      "skipped" : 0,
      "passed" : 12,
      "unknown" : 0,
      "total" : 30
    },
    "items" : [ {
      "uid" : "7222d508dffc5a32",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/21//#testresult/7222d508dffc5a32",
      "status" : "passed",
      "time" : {
        "start" : 1649175048397,
        "stop" : 1649175049151,
        "duration" : 754
      }
    }, {
      "uid" : "1fd6f28c6713b934",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/1fd6f28c6713b934",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f139dcb9b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649174532009,
        "stop" : 1649174532009,
        "duration" : 0
      }
    }, {
      "uid" : "eea038cfe62ec367",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/eea038cfe62ec367",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b9b15de0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173716768,
        "stop" : 1649173716768,
        "duration" : 0
      }
    }, {
      "uid" : "edf879c1c060081a",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/edf879c1c060081a",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfa4d65de0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649173131329,
        "stop" : 1649173131329,
        "duration" : 0
      }
    }, {
      "uid" : "3d399bfcbf8242fa",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/15//#testresult/3d399bfcbf8242fa",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f148011db70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649172350635,
        "stop" : 1649172350635,
        "duration" : 0
      }
    }, {
      "uid" : "8a7e0f624f3b0c11",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/8a7e0f624f3b0c11",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb217c32650>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649170175375,
        "stop" : 1649170175375,
        "duration" : 0
      }
    }, {
      "uid" : "e24558da938d92ef",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/11//#testresult/e24558da938d92ef",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba61fb9de0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649167885663,
        "stop" : 1649167885663,
        "duration" : 0
      }
    }, {
      "uid" : "ea2244b7a9feaa26",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/10//#testresult/ea2244b7a9feaa26",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b12635b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166993570,
        "stop" : 1649166993570,
        "duration" : 0
      }
    }, {
      "uid" : "257170fd0a3a80cf",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/9//#testresult/257170fd0a3a80cf",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04e82d5de0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649166019066,
        "stop" : 1649166019066,
        "duration" : 0
      }
    }, {
      "uid" : "1d80904073a735cc",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/20//#testresult/1d80904073a735cc",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False",
      "time" : {
        "start" : 1649165668388,
        "stop" : 1649165669100,
        "duration" : 712
      }
    }, {
      "uid" : "22cc18f00a1cf0ae",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/19//#testresult/22cc18f00a1cf0ae",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False",
      "time" : {
        "start" : 1649165607884,
        "stop" : 1649165608696,
        "duration" : 812
      }
    }, {
      "uid" : "3864d48949a32a4b",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/7//#testresult/3864d48949a32a4b",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69c00f5c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649165600036,
        "stop" : 1649165600036,
        "duration" : 0
      }
    }, {
      "uid" : "2df502601f9bbcec",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/6//#testresult/2df502601f9bbcec",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe6809ec8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649110749784,
        "stop" : 1649110749784,
        "duration" : 0
      }
    }, {
      "uid" : "a811dbc725738448",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/18//#testresult/a811dbc725738448",
      "status" : "passed",
      "time" : {
        "start" : 1649110729602,
        "stop" : 1649110730403,
        "duration" : 801
      }
    }, {
      "uid" : "4ebfbca5d49bb805",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/17//#testresult/4ebfbca5d49bb805",
      "status" : "passed",
      "time" : {
        "start" : 1649109321731,
        "stop" : 1649109322377,
        "duration" : 646
      }
    }, {
      "uid" : "478735d34d80760",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/4//#testresult/478735d34d80760",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff130cd0820>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109176032,
        "stop" : 1649109176032,
        "duration" : 0
      }
    }, {
      "uid" : "10765b1d788039fc",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/3//#testresult/10765b1d788039fc",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56549cc850>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649109036493,
        "stop" : 1649109036493,
        "duration" : 0
      }
    }, {
      "uid" : "3e0125074b178a3a",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/14//#testresult/3e0125074b178a3a",
      "status" : "passed",
      "time" : {
        "start" : 1649108803930,
        "stop" : 1649108804774,
        "duration" : 844
      }
    }, {
      "uid" : "483ba636da7627bf",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/13//#testresult/483ba636da7627bf",
      "status" : "passed",
      "time" : {
        "start" : 1649108544889,
        "stop" : 1649108545644,
        "duration" : 755
      }
    }, {
      "uid" : "9f9b4a8cba06bec",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/1//#testresult/9f9b4a8cba06bec",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14f0008b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649108544826,
        "stop" : 1649108544826,
        "duration" : 0
      }
    } ]
  }
}